train:
  batch_size: 2
  seed: 42
  epochs: 1000
  shuffle: true
  resume_train: false
  eval: true
  num_workers: 0  
  save: true
  save_path: checkpoints/pretrain
  log_interval: 100
  mask_ratio: 0.15
  steps: 1
  loss_denoise: 1.0
  loss_pred_noise: 0.2
  optimizer:
    type: AdamW
    lr: 0.0001
    weight_decay: 0.000
    dropout: 0.0



model:
  name: PaiNN
  backbone: PaiNN
  hidden_dim: 128
  sigma_begin: 10
  sigma_end: 0.01
  num_noise_level: 50
  order: 3
  cutoff: null 
  noise_type: riemann
  pred_mode: energy
  no_edge_types: False
  sigma_order: 2
  use_last_only: True
  layernorm: False
  max_atom_type: 100
  charge_power: 2
  n_layers: 3
  out_decoder: 43





